blog/article/urls.py
# coding=utf-8
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'article'
urlpatterns =[
    url(r'^$', views.home, name= 'home'),
    url(r'^(?P<id>\d+)/$', views.detail, name= 'detail'),
    url(r'^test/$', views.test),
    url(r'^archives/$',views.archives, name='archives'),
    url(r'^about_me/$', views.about_me, name='about_me'),
    url(r'^tag/(?P<tag>\w+)/$', views.search_tag, name='search_tag'),
    url(r'search/$', views.blog_search, name='search')

]

blog/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from article import views
from article import urls as urll
urlpatterns = [
    path('article/', include('article.urls')),
   #  url('^$', views.home, name= 'home'),
    path('admin/', admin.site.urls),
    url(r'comment/', include('comments.urls'))

]

blog/comments/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

app_name= 'comments'
urlpatterns= [
    url(r'^(?P<id>[0-9]+)/$', views.article_comment, name= 'article_comment'),
]

blog/article/models.py
from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.contrib.auth.models import User

#@python_2_unicode_compatible
#class Category(models.Model):


class Article(models.Model):
    title = models.CharField(max_length= 200)
    category = models.CharField(max_length= 100, blank= True)
    date_time = models.DateTimeField(auto_now_add= True)
    content = models.TextField(blank= True, null= True)
    excerpt = models.CharField(max_length=200, blank= True, null= True)
    author= models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:detail', kwargs={'id': self.id})

   # def get_category():
   #     ret
    class Meta:
        ordering = ['-date_time']

blog/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
    name= models.CharField(max_length= 100)
    email= models.EmailField(max_length= 200)
    url= models.URLField(blank= True)
    text= models.TextField()
    date_time= models.DateTimeField(auto_now_add= True)
    article= models.ForeignKey('article.Article', on_delete = models.CASCADE)

    def __str__(self):
        return self.text[:20]

blog/article/forms.py
# coding=utf-8
from django import forms
from pagedown.widgets import AdminPagedownWidget
from .models import Article

class ArticleForm(forms.ModelForm):
   content = forms.CharField(widget=AdminPagedownWidget(), required=False,
   label='')

blog/comments/forms.py
# coding=utf-8
from django import forms
from .models import Comment
from pagedown.widgets import AdminPagedownWidget

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields= ['name', 'email', 'text']

class ArticleForm(forms.ModelForm):
    content = forms.CharField(widget=AdminPagedownWidget(), required=False, label='')

blog/article/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article
from datetime import datetime
from django.http import Http404
from comments.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import markdown

def home(request):
    post_list = Article.objects.all()  # 获取全部的Article对象
  #  paginator = Paginator(posts, 2)  # 每页显示两个
  #  page = request.GET.get('page')
  #  try:
  #      post_list = paginator.page(page)
  #  except PageNotAnInteger:
  #      post_list = paginator.page(1)
  #  except EmptyPage:
  #      post_list = paginator.paginator(paginator.num_pages)
    return render(request, 'home.html', {'post_list': post_list})

def detail(request, id):
    post = get_object_or_404(Article, id= id)
    post.content = markdown.markdown(post.content,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list
    }
    return render(request, 'post.html', context= context)

def test(request) :
    return render(request, 'test.html', {'current_time': datetime.now()})

def about_me(request):
    post = get_object_or_404(Article, title='aboutme' )
    post.content = markdown.markdown(post.content,
                                     extensions=[
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'markdown.extensions.toc',
                                     ])

    return render(request, 'aboutme.html', {'post': post})

def archives(request):
    try:
        post_list = Article.objects.all()
    except Article.DoesNotExist :
        raise Http404
    return render(request, 'archives.html', {'post_list' : post_list,
                                            'error' : False})

def search_tag(request, tag):
    try:
        post_list = Article.objects.filter(category__iexact = tag)
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'tag.html', {'post_list': post_list})

def blog_search(request):
    if 's' in request.GET:
        s = request.GET['s']
        if not s:
            return render(request, 'home.html')
        else:
            post_list = Article.objects.filter(title__icontains = s)
            if len(post_list) == 0:
                return render(request, 'archives.html', { 'post_list': post_list,
                                                          'error': True
                })
            else:
                return render(request, 'archives.html', {'post_list': post_list,
                                                         'error': False})
    return redirect('/')

blog/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from article.models import Article
from .models import Comment
from .forms import CommentForm

def article_comment(request, id):
    post = get_object_or_404(Article, id= id)
    if request.method == 'POST':
        form= CommentForm(request.POST)

        if form.is_valid():
            comment= form.save(commit= False)
            comment.article = post
            comment.save()
            return redirect(post)

        else:
            comment_list= post.comment_set.all()
            context= {'post': post,
                      'form': form,
                      'comment_list':comment_list
                      }
            return render(request, 'article/post.html', context= context)
    return redirect(post)

blog/article/templates/aboutme.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
<div class="posts">
        <section class="post">
            <header class="post-header">

            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|safe}}

                    </p>
                </div>
        </section>


</div><!-- /.blog-post -->
{% endblock %}

blog/article/templates/archives.html
{% extends "base.html" %}

{% block content %}
<div class="posts">
    {% if error %}
        <h2 class="post-title">没有相关文章题目</h2>
    {% else %}
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url "article:detail" id=post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time: <a class="post-author" href="#">{{ post.date_time |date:'Y /m /d'}}</a>&nbsp&nbsp
                        Category: <a class="post-category post-category-pure" href="{% url "article:search_tag" tag=post.category %}">{{ post.category }}</a>&nbsp&nbsp
                       <!-- Tag:
                          {% for tag in post.tag.all %}
                            <a class="post-category post-category-pure" href="#">{{ tag }}</a>
                          {% endfor %}
                        -->
                    </p>
            </header>
        </section>
    {% endfor %}
    {% endif %}
</div><!-- /.blog-post -->
{% endblock %}      

blog/article/templates/base.html
<!--base.html-->
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>李布斯的博客</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/blog.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/github.css">
   <!-- <link rel="stylesheet" href="{% static 'blog/css/custom.css'%}">
-->
</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title"><a href="{% url "article:home" %}">Geeks Booth Li Blog</a></h1>
            <h2 class="brand-tagline">戏青衣-戏里梦青衣</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/qingyibaimao">Github</a>
                    </li>

                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url "article:about_me" %}">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-error pure-button" href="https://y.qq.com/w/taoge.html?id=3224170777">music</a>
                    </li>

                    <li class="nav-item">
                        <a class="button-error pure-button" href="https://www.jianshu.com/u/340d706431de">简书</a>
                    </li>


                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url "article:home" %}">主页</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url "article:archives" %}">归档</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/admin">登录</a>
                    </li>
                    <li>
                        <form class="pure-form" action="search/" method="get">
                            <input class="pure-input-3-3" type="text", name="s" placeholder="search">
                        </form>
                    </li>

                </ul>
            </nav>
        </div>
    </div>


    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul>
                        <li><a href="{% url "article:about_me" %}">About Me</a></li>
                        <li><a href="http://twitter.com/yuilibrary/">Twitter</a></li>
                        <li><a href="http://github.com/yahoo/pure/">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

blog/article/templates/home.html
<!--home.html-->
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url "article:detail" id=post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:"Y /m /d"}}</a>
                        <a class="post-category post-category-js" href="#">{{ post.category }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|custom_markdown|truncatewords_html:8  }}

                    </p>
                </div>
                <a class="pure-button" href="{% url "article:detail" id=post.id %}">Read More >>> </a>
        </section>

    {% endfor %}
    <!--
    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
        <div>
            <ul>
                {% if post_list.has_previous %}
                <li><a href="?page={{post_list.previous_page_number}}">上一页</a></li>
            {% endif %}
      {% if post_list.has_next %}
        <li><a href="?page={{ post_list.next_page_number }}">下一页</a></li>
      {% endif %}
      </ul>
      </div>
    {% endif %}
    -->
</div><!-- /.blog-post -->
{% endblock %}

blog/article/templates/post.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
<div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time|date:"Y /m /d"}}</a>
                        &nbsp;<a class="post-author" href="#">{{ post.author}}</a>
                        <a class="post-category post-category-js" href="#">{{ post.category }}</a>

                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|safe}}

                    </p>
                </div>
        </section>
     <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url "comments:article_comment" post.id %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>

        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list|length}}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.date_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无更多评论
                {% endfor %}
            </ul>
        </div>
    </section>

</div><!-- /.blog-post -->
{% endblock %}

blog/article/templates/tag.html
{% extends "base.html" %}

{% block pagetitle %}
  {% for post in post_list %}
  <title>{{ post.category }}</title>
  {% endfor %}
{% endblock %}

{% block content %}
  <div class="blog-post">
    {% for post in post_list %}
      <h2 class="blog-post-title"><a href="{% url "article:detail" id=post.id %}">{{ post.title }}</a></h2>
        <p class="blog-post-meta">
          发布：<a class="btn btn-xs btn-info">{{ post.date_time | date:'Y/m/d' }}</a>&nbsp&nbsp
          目录：<a class="btn btn-xs btn-info" href="{% url "article:search_tag" post.category %}">{{ post.category | title}}</a>&nbsp&nbsp
         <!-- 标签：
          {% for tag in post.tag.all %}
            <a class="btn btn-xs btn-info" href="">{{ tag }}</a></p>
          {% endfor %}
          -->
        </p>
        <br />
    {% endfor %}
  </div><!-- /.blog-post -->
{% endblock %}

blog/article/templates/test.html
<html>
    <head>
        <title>Just test template</title>
        <style>
            body {
               background-color: red;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
    </head>
    <body>
        <h1>Hello World!</h1>
        <strong>{{ current_time }}</strong>
    </body>
</html>